#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Запуск форматирования и линтинга через lint-staged
npx lint-staged

# Запуск проверки на максимальный размер файла (anti-monolith)
./scripts/check-file-length.sh
